# Generated by Django 5.0.4 on 2024-04-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_profile'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.profile'),
        ),
    ]
